### PR TITLE
Fix OAuth redirection to previous url after LOGIN

### LINKED ISSUE #6233: Redirect to same page after oauth login
I found this code is again broken.
Let's fix this first.

### PR DESCRIPTION
**Pull request by Uzay-G**
Fixes #6233 

The `origin` parameter for the oauth login was always empty although that was the parameter that told the omniauth where to redirect.

There were two different cases here where we need to solve the redirection. One, the user uses the signup modal to log in. Two, the user goes to a page restricted for logged in users and is redirected to the login page.

In the first one, we want to redirect the user to the page he is currently on when he is filling the signup overlay. We can access this with url in Rails with `request.origin_url`. For the second case, the user is on the "/login" page which is not where he wants to be redirected. To fix this, I edited the `require_login` filter that redirects to the login page to set a `return_to` parameter:
```ruby
def require_user
    unless current_user
      store_location
      flash[:warning] ||= I18n.t('application_controller.must_be_logged_in_to_access')
     # what I added
      redirect_to "/login?return_to=" + request.fullpath
      false
    end
end
```
So, if the user is trying to post a node at https://publiclab.org/post, the `require_login` function is called and  he will be redirected to `https://publiclab.org/login?return_to=/post`. We can then set the origin attribute for oauth to `params[:return_to]`. So now that these two problems could be solved individually, I needed to pair the two so that the origin parameter be set to the `return_to` parameter when there is one and otherwise, when the modal is being used, the origin is set to the current url. 

This is the result:
`<a href="/auth/provider?origin=<%= params[:return_to] || request.original_url %>"`

So for example, if user1 is at https://publiclab.org/about and they click the login modal, they are still on the same page and the origin will be set to `request.original_url` -> https://publiclab.org/about. But if the `params[:return_to]` is set, he will be redirected to the page he was trying to go to before logging in.

This is a demo of the working redirection for both cases:
correct-login

I also added a test to the users_sessions controller for the oauth redirection!

Although I could not claim this task on the GCI dashboard, it has been open for a long time and I wanted to solve it because this issue was interfering with the testing of my pull request #7005 
It was really fun to investigate all the mechanisms for the issue and then documenting the fix.
I hope you're okay that I submitted the pull request without claiming it on GCI and I can retract it if you want but I could not work on tests for the other pull request because of this problem.

Thanks! :+1:

### CODE REVIEW

**Comment by Uzay-G** [comment]
For now, the initial sign-in does not redirect to dashboard, but I have the changes to implement that if you want me too.

**Comment by SidharthBansal** [comment]
Why you have changed all the tests?

**Comment by SidharthBansal** [comment]
This leads to one more harder issues for CDSM, you can claim it after this. Just you have to write the tests in MK, SWB and/or Plots. I am not sure. We can discuss after this is merged.

**Comment by Uzay-G** [comment]
I had to change the tests because when users were going to a restricted page, the were redirected to login + the `return_to` param. I don't really understand what you mean by your second message.

**Comment by SidharthBansal** [comment]
> I don't really understand what you mean by your second message.

We will require a pr after merging 7113

**Comment by Uzay-G** [comment]
> We will require a pr after merging 7113
With that purpose?

**Comment by SidharthBansal** [comment]
> I had to change the tests because when users were going to a restricted page, the were redirected to login + the return_to param. 

Please explain with an example

**Comment by SidharthBansal** [comment]
Please note that this pr affects Mapknitter and spectralworkbench repo, so we need to be extra carefully before merging it.
Thanks

**Comment by Uzay-G** [comment]
Ok, here's an example before the change:
```ruby
  test 'non-registered user should not be able to see spam_revisions page' do
    UserSession.create(users(:admin))
    UserSession.find.destroy

    get :spam_revisions

    assert_equal 'You must be logged in to access this page', flash[:warning]
    assert_redirected_to '/login'
  end
```
With my changes, when the user goes to a login-restricted page, we store a `return_to` parameter in the url which is where we will redirect the user after logging in. So if he has tried to go to to `/spam/revisions/` endpoint but was blocked, his `return_to` is `/spam/revisions` and he is redirected to `/login?return_to=/spam/revisions/` and not `/login`.
So I had to change the tests to fix that error.

**Comment by SidharthBansal** [comment]
> With that purpose?

In short, Mapknitter and SpectralWorkBench Authentication depends on Plots2 authentication System. Plots2 Auth system in indeed dependent on Oauth and omniauth.

So, we need tests for mapknitter and spectralworkbench. May be we will not require them. I have to investigate it or may be you can. Problem with your investigation: if you don't require tests then you will get 3points for research/investigation, but if there would be tests then it can be another 15 points task. 

You can do it when your pr is not reviewed.

**Comment by SidharthBansal** [comment]
I mean, when you are in a free state.

**Comment by SidharthBansal** [comment]
You are working on 3 repo work in this pr. So, please keep checking things. 
It's really great to see that you come so far. :-)

**Comment by Uzay-G** [comment]
Yeah ok no problem. So I would test the oauth of SWB and mapknitter if they are affected by these changes?
Thanks! I'm learning so much about Rails it's nice! :+1:

**Comment by SidharthBansal** [comment]
Difficult thing, but we have to:
Please check these things on localhost and provide screenshots.
Thanks

**Comment by SidharthBansal** [comment]
by these things I mean tests in this pr.

**Comment by Uzay-G** [comment]
Sorry, I posted a gif for the working redirection. Do you want me to provide screenshots for the oauth of Mapknitter and SWB to see if they are affected?

**Comment by SidharthBansal** [comment]
> Sorry, I posted a gif for the working redirection. Do you want me to provide screenshots for the oauth of Mapknitter and SWB to see if they are affected?

 I am asking after rectified tests in #7113 
I am not asking for MK and SWB work now.

**Comment by SidharthBansal** [comment]
Please claim the tasks for installation of MK and SWB and get points

**Comment by Uzay-G** [comment]
Alright I will claim them when I am not on another task

**Comment by SidharthBansal** [comment]
ok

**Comment by Uzay-G** [comment]
Sorry, I don't really understand what screenshots you want me to provide for the tests. Do you want me to follow the path on localhost of the example test I showed to make sure everything is working?

**Comment by Uzay-G** [comment]
Here is an example of why I changed the tests:
redirection-tests

As you can see, with my changes, the non-logged in user gets redirected to `/login?return_to=/login_restricted_page`. That's why I changed the tests.

**Comment by SidharthBansal** [comment]
What happens after you login in above screenshot?

**Comment by Uzay-G** [comment]
After I login, I get redirected to `/spam/revisions` but since I am not an admin in that video, I then get redirected to the root url.

**Comment by SidharthBansal** [comment]
What if you login as an admin?

**Comment by SidharthBansal** [comment]
Try and provide gif/video

**Comment by Uzay-G** [comment]
Yeah I will do it. Do you know how I can create a new admin user through oauth?

**Comment by SidharthBansal** [comment]
Hello, I have some tasks for you while I am busy:
1. Set up MK, SWB and plots2 on local and try to connect these apps together so that MK and SWB will use OAuth of plots2. It is tough but fun. I will help you in that
2. This PR is for login or sign in or authentication( authentication means login + signup). 
Please create similar pr for sign up and change names accordingly if needed.

**Comment by SidharthBansal** [comment]
Use existing admin account. Link them to providers.

**Comment by Uzay-G** [comment]
Oh ok thanks!

**Comment by SidharthBansal** [comment]
1. login as admin
2. set up google developer app
3. go to edit profile section 
4. login with google

**Comment by SidharthBansal** [comment]
Create github  app instead of google developer app
Refer https://github.com/publiclab/plots2/issues/2856
it is simple

**Comment by SidharthBansal** [comment]
Refer https://github.com/publiclab/plots2/blob/master/doc/LOGIN_SYSTEMS.md

**Comment by SidharthBansal** [comment]
I will be there to guide you. I am not that busy so don't worry
Once #7113 for login and a pr for sign up redirection is complete, then we can go to pr for tests of Mk and pr for tests for SWB login.

Tests for SWB & MK contains 15 points separately if you need them. Else for investigation you will get 5 points apart from redirection issues. 

We will be fair in giving you points, so don't worry.

**Comment by SidharthBansal** [comment]
Please get points for installation of MK, SWB and plots2 asap. :-)

**Comment by Uzay-G** [comment]
Oh yeah I just took care of that :+1:!

**Comment by SidharthBansal** [comment]
In case of any confusion then please feel free to ask( in points/ login systems of MK or SWB or PLots2 etc.)

**Comment by SidharthBansal** [comment]
@Uzay-G wherever you find any login/authentication/sign up related issues/pr then kindly add LOGIN & SIGNUP Milestone. If you are unable to do so then kindly ping me

**Comment by Uzay-G** [comment]
Hey! @jywarren and @SidharthBansal can we merge this so I can open new pull requests for #5600 and #3367. Thanks!

**Comment by SidharthBansal** [comment]
Hi, I am going for sleep right now. If you are fine with reviewing it on
Sunday then please do other tasks in the meantime.
I will review it soon and let you know. :-)

**Comment by Uzay-G** [comment]
Hey @SidharthBansal I modified the `sessions_controller` so that when a user signs up for the first time, they are not redirected to the previous page but to the dashboard. This modification was discussed in the issue for this pull request.

**Comment by Uzay-G** [comment]
I will also add a test to make sure that when a user signs up through oauth for the first time, they are redirected to the dashboard and **not** the page they were on before signing up.

File: app/controllers/user_sessions_controller.rb [hunk 1]
```diff
@@ -77,15 +77,8 @@ def handle_social_login_flow(auth)
             return_to = session[:openid_return_to]
             session[:openid_return_to] = nil
             redirect_to return_to + hash_params
-          elsif params[:return_to] && params[:return_to].split('/')[0..3] == ["", "subscribe", "multiple", "tag"]
```
Comment (SidharthBansal) [inline app/controllers/user_sessions_controller.rb]: why have you removed it? This was a feature I built. Any special reasons?

Comment (Uzay-G) [reply app/controllers/user_sessions_controller.rb]: I removed it because in the issue and when we chatted about oauth, you said when users sign up they should be redirected to the dashboard. This is the code that handles that part:
https://github.com/publiclab/plots2/blob/c4f849d0c9f3a5d54ad9e0ebd6b433ab42dc47ae/app/controllers/user_sessions_controller.rb#L66-L82

So as you can see, if a user without an account goes to `/subscribe/multiple/tag/water` and then they are prompted to sign up, when they signup they will be redirected to the subscriptions instead of the dashboard.

Comment (SidharthBansal) [reply app/controllers/user_sessions_controller.rb]: I think this part should be discussed separately. Is this needed in this pr?
Title says LOGIN. Isn't it?
We intentionally created this feature due to some reason. Can you please open up an issue for discussion and remove these changes from here if they don't interfere with the OAuth changes?

Comment (Uzay-G) [reply app/controllers/user_sessions_controller.rb]: Yeah no problem

**Comment by Uzay-G** [comment]
I will open up a new issue for signup redirection

File: app/controllers/user_sessions_controller.rb (hunk 1 above)
Comment (SidharthBansal) [reply app/controllers/user_sessions_controller.rb]: Sure

**Comment by SidharthBansal** [comment]
can I review this pr now?

File: test/functional/user_sessions_controller_test.rb [hunk 2]
```diff
@@ -266,4 +266,12 @@ class UserSessionsControllerTest < ActionController::TestCase
     post :destroy
     assert_equal "Successfully logged out.",  flash[:notice]
   end
+  
+  test "redirects tto previous page when logging in through oauth" do
```
Comment (SidharthBansal) [inline test/functional/user_sessions_controller_test.rb]: to typo

**Comment by SidharthBansal** [comment]
@IshaGupta18 kindly review this.
LGTM from my side

**Comment by SidharthBansal** [comment]
@ananyaarun kindly review this

**Comment by SidharthBansal** [comment]
5 points to the PR and 3 points to test. So 8 points.

**Comment by Uzay-G** [comment]
Thanks for your great help with this issue @SidharthBansal! I will claim the task on the dashboard

**Comment by SidharthBansal** [comment]
Marks given
