### PR TITLE
initial fix attempt for comment/answer markdown

### LINKED ISSUE #2604: Parsing of markdown (formatting) of answers and comments is broken
Formatting of answers to questions and comments on answers ignores line breaks and paragraph breaks and does not display images or make urls hot.

https://publiclab.org/questions/nshapiro/03-27-2018/what-data-logger-will-work-with-my-portable-hcho-meter#answer-927-comment-19332

https://publiclab.org/questions/JLJ/04-09-2018/calculating-ndvi-using-pinoir-camera-and-blue-filter

### What's your PublicLab.org username?

cfastie

### Browser, version, and operating system

Chrome, windows

### PR DESCRIPTION
**Pull request by jywarren**
fixes #2604

Starting with tests!

### CODE REVIEW

**Comment by jywarren** [comment]
This is complete, but I can't figure out how to write the `assert_select` query to check! Ugh...

File: test/functional/questions_controller_test.rb [hunk 1]
```diff
@@ -22,12 +22,39 @@ def setup
...
 
+  test 'question comment markdown and autolinking works' do
+    node = nodes(:question)
+    assert node.comments.length > 0
+    comment = node.comments.last
+    comment.comment = 'Test **markdown** and http://links.com'
+
+    get :show, id: node.id
+
+    assert_select 'strong', 'markdown'
```
Comment (siaw23) [inline test/functional/questions_controller_test.rb]: @jywarren don't know how to pull this PR to test locally so i cant test. but instead of `"strong"` can you please try `"b"`?

**Comment by jywarren** [comment]
I actually started with b - but I don't think the assertion is failing,
it's actually the syntax of assert_select that's causing an error!

There should be instructions under "command line" below, but I think it
should be "git pull jywarren comment-markdown"

**Comment by jywarren** [comment]
And thanks!!!

**Comment by siaw23** [comment]
it's weird that i can't find your branch here to pull https://github.com/publiclab/plots2/branches/all?utf8=%E2%9C%93&query=comment :/ @jywarren

**Comment by jywarren** [comment]
Ah it's because it's a branch on my fork at jywarren/plots2!

**Comment by jywarren** [comment]
Hmm, no luck?

**Comment by siaw23** [comment]
i stopped investigating last night cause it was time for sleep but today i looked into it and made some changes: f11e88f and made some comments in the file.

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !

Adding this line solves this .

`comment.save!` in the tests .

**Comment by sagarpreet-chadha** [comment]
screen shot 2018-04-11 at 6 37 13 pm

**Comment by siaw23** [comment]
@sagarpreet-chadha solution i went after. my history shows me doing `node.save!` 🤦🏾‍♂️ thank you!

**Comment by jywarren** [comment]
I resolved a small conflict, let's see how this does! Thanks everybody for helping out, i really appreciate it. @Fastie is struggling a bit with commenting while this is broken.

**Comment by jywarren** [comment]
Copied this solution to the last test -- great catch. I feel a bit silly for missing that!

**Comment by jywarren** [comment]
Phew! Deploying to stable to check.

**Comment by jywarren** [comment]
Confirmed, it works!!! 🎉 🎆 🙌 👍

**Comment by sagarpreet-chadha** [comment]
Awesome!!!!
