### PR TITLE
add PDF to images fixtures and fix PDF upload display

### LINKED ISSUE #10120: Non-image upload (PDF) to Google Cloud Storage not working (from wiki pages)
Dragging in a PDF to this page: https://publiclab.org/wiki/edit/frac-sand-mining-pollution-incident-report-form-and-guide

correctly processed and then generated and inserted this markup:

```html
<a href="/i/44764"><i class="fa fa-file"></i> via_main_menu_July_2021.pdf</a>
```

That link redirects to:

https://storage.googleapis.com/publiclab-production/public/system/images/photos/000/044/764/large/via_main_menu_July_2021.pdf

However that URL shows:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: publiclab-production/public/system/images/photos/000/044/764/large/via_main_menu_July_2021.pdf</Details>
</Error>
```

Could we be seeing a redirect issue affecting non-image files?

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #10120

### CODE REVIEW

File: test/functional/images_controller_test.rb [hunk 1]
```diff
@@ -7,16 +7,23 @@ def setup
...
+    assert_redirected_to images(:one).path(:medium)
+    get :shortlink, params: { id: images(:one).id, size: 'm' }
+    assert_redirected_to images(:one).path(:medium)
+    get :shortlink, params: { id: images(:one).id, size: 'thumbnail' }
+    assert_redirected_to images(:one).path(:thumb)
+    get :shortlink, params: { id: images(:one).id, s: 'thumbnail' }
+    assert_redirected_to images(:one).path(:thumb)
+  end
+  
+  test "image shortlinks redirect properly with non-images, like PDFs" do
```
Comment (jywarren) [inline test/functional/images_controller_test.rb:22]: Excellent these failed before filing the fix:

```
ImagesControllerTest#test_image_shortlinks_redirect_properly_with_non-images,_like_PDFs (125.88s)
        Expected response to be a redirect to <http://test.host/public/system/images/photos/250/665/868/original/test.pdf> but was a redirect to <http://test.host/public/system/images/photos/250/665/868/large/test.pdf>.
        Expected "http://test.host/public/system/images/photos/250/665/868/original/test.pdf" to be === "http://test.host/public/system/images/photos/250/665/868/large/test.pdf".
        test/functional/images_controller_test.rb:24:in `block in <class:ImagesControllerTest>'
```
