### PR TITLE
Fixes parsing multiple subscription signup #8166

### LINKED ISSUE #8166: Error on parsing multiple subscription signup
I experienced this upon using the multi signup at https://publiclab.org/tag/water-quality

Screenshot_20200718-075953

Sentry Issue: [PLOTS2-R4](https://sentry.io/organizations/publiclab/issues/1695204051/?referrer=github_integration)

```
NoMethodError: undefined method `join' for "first-time-poster,gulf-coast":String
  app/controllers/subscription_controller.rb:162:in `block (2 levels) in multiple_add'
    flash[:notice] = "You are now following #{params[:tagnames].join(', ')}."
  app/controllers/subscription_controller.rb:157:in `multiple_add'
    respond_with do |format|
...
(104 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #8166

### CODE REVIEW

**Comment by jywarren** [comment]
Ohhhhhhhh

```

 FAIL["test_should_redirect_properly_when_subscribing_to_multiple_tags", #<Minitest::Reporters::Suite:0x000000001062e5e8 @name="SubscriptionControllerTest">, 29.610231640999984]
 test_should_redirect_properly_when_subscribing_to_multiple_tags#SubscriptionControllerTest (29.61s)
        --- expected
        +++ actual
        @@ -1 +1 @@
        -"You are now following [\"blog\", \"kites\", \"\", \"balloon\", \"awesome\"]."
        +"You are now following blog, kites, , balloon, awesome."
        test/functional/subscription_controller_test.rb:64:in `block in <class:SubscriptionControllerTest>'
```

File: app/controllers/subscription_controller.rb [hunk 1]
```diff
@@ -159,7 +159,7 @@ def multiple_add
               if request.xhr?
                 render json: true
               else
-                flash[:notice] = "You are now following #{params[:tagnames].join(', ')}."
+                flash[:notice] = "You are now following #{params[:tagnames]}."
```
Comment (jywarren) [inline app/controllers/subscription_controller.rb:162]: Hmm.

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/blob/fixes-multisubscription/test/functional/subscription_controller_test.rb#L64

**Comment by jywarren** [comment]
Nope... 😭 

```
ERROR["test_should_redirect_properly_when_subscribing_to_multiple_tags", #<Minitest::Reporters::Suite:0x0000000011550030 @name="SubscriptionControllerTest">, 52.44063293400001]
 test_should_redirect_properly_when_subscribing_to_multiple_tags#SubscriptionControllerTest (52.44s)
Minitest::UnexpectedError:         NoMethodError: undefined method `join' for nil:NilClass
            app/controllers/subscription_controller.rb:162:in `block (2 levels) in multiple_add'
            app/controllers/subscription_controller.rb:157:in `multiple_add'
            test/functional/subscription_controller_test.rb:62:in `block in <class:SubscriptionControllerTest>'
ERROR["test_should_subscribe_to_multiple_tags", #<Minitest::Reporters::Suite:0x00000000118bec30 @name="SubscriptionControllerTest">, 52.558379075000005]
 test_should_subscribe_to_multiple_tags#SubscriptionControllerTest (52.56s)
Minitest::UnexpectedError:         NoMethodError: undefined method `join' for nil:NilClass
            app/controllers/subscription_controller.rb:162:in `block (2 levels) in multiple_add'
            app/controllers/subscription_controller.rb:157:in `multiple_add'
            test/functional/subscription_controller_test.rb:31:in `block in <class:SubscriptionControllerTest>'
```

**Comment by jywarren** [comment]
Hooray!!
