### PR TITLE
Fix bug in new graph_making method

### LINKED ISSUE #5204: Investigate stats results
While adding a range to graph on tags stats I noticed some data was being emitted when using the new method https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L197-#L208

This is to make the same is not happening in /stats page and also add tests for the method.

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #5204 

* Add tests for the methods
* Preset range to 3 months ago in stats

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by jywarren** [comment]
Looks great, thanks for the good tests, Cess!

File: test/unit/node_test.rb [hunk 1]
```diff
@@ -425,8 +431,13 @@ class NodeTest < ActiveSupport::TestCase
...
-    graph = Node.contribution_graph_making
-    assert_not_nil graph
-    assert graph.class, Hash
+    graph_notes = Node.contribution_graph_making('note', @start, @fin)
+    graph_wiki = Node.contribution_graph_making('page', @start, @fin)
+    notes = Node.where(type: 'note', created: @start.to_i..@fin.to_i).count
+    wiki = Node.where(type: 'page', created: @start.to_i..@fin.to_i).count
+
+    assert graph_notes.class, Hash
+    assert_equal notes, graph_notes.values.sum
```
Comment (jywarren) [inline test/unit/node_test.rb]: Ah, i'm just going to comment this one out for now!
