### PR TITLE
Use node views cache

### LINKED ISSUE #1196: Impressionist counter_cache not working
### What happened just before the problem occurred

We've installed the [impressionist gem](https://github.com/charlotte-ruby/impressionist) and are successfully counting unique impressions on pages now. But the "counter cache" setup (which would keep a column on the `node` table updated with a calculated tally of views) is not working, though that's in the code:

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L181

We've temporarily based `node.totalcount` on the sum of `node.legacy_views + node.impressions_count`:

https://github.com/publiclab/plots2/blob/master/app/models/node.rb#L183-L187

However, if we can get this line of the tests passing, we can re-institute the cached value, which will improve performance for node page views (notes and wikis):

https://github.com/publiclab/plots2/blob/master/test/functional/notes_controller_test.rb#L74

### PR DESCRIPTION
**Pull request by alonpeer**
Fixes #1196

This should improve performance of various page loads, as it avoids
running COUNT() queries on the impressions table, and instead uses the
views value, which the impressions gem keeps up-to-date.

Notice that I update the tests to `.reload` the node before reading values,
because ActiveRecord caches those, which is why tests fail without it.

---

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by alonpeer** [comment]
@publiclab/reviewers @gauravano @jywarren I accidentally deleted my branch and closed PR #5248. This PR replaces it and fixes the conflict.

File: test/functional/notes_controller_test.rb [hunk 1]
```diff
@@ -81,7 +81,7 @@ def teardown
     assert_equal '0.0.0.0', Impression.last.ip_address
     Impression.last.update_attribute('ip_address', '0.0.0.1')
 
-    assert_difference 'note.totalviews', 1 do
+    assert_difference 'note.reload.totalviews', 1 do
```
Comment (jywarren) [inline test/functional/notes_controller_test.rb]: Oh interesting. Can we add a bit of documentation about this usage? I'm not familiar with it! Thanks!

Comment (jywarren) [reply test/functional/notes_controller_test.rb]: Ah! I see your note above:

> Notice that I update the tests to .reload the node before reading values,
because ActiveRecord caches those, which is why tests fail without it.

Does it cache it just within the context of the test? Any other situations where we'd need to flush the cache? Thank you!!!

Comment (alonpeer) [reply test/functional/notes_controller_test.rb]: From my experience with Rails, this is a tests-specific hack. The cache is on request level, so it shouldn't affect any production paths. 
In this specific test, we're reading the note, then changing the impressions, then trying to read a value from the note. Since the note is cached (i.e. already read), we have to force it to reload from DB, so that we get the most recent value of `totalviews`.

**Comment by jywarren** [comment]
All right -- this is great then! Merging now!!! 🎉 Thanks for your patience!!!
