### PR TITLE
Bug: Fix CLICK-to-Upload Image Cross-Wiring Issues

### LINKED ISSUE #8926: Issue: Add Unique HTML IDs to Comment Forms to Fix Image Upload Cross-Wiring Issues
## `Description`
Creating a fresh issue page for this complex bug that appears in many forms. See #8670 and #8478 for two examples of this bug in action. Also see current PR #8897 (awaiting review) that fixes a small piece of this bug.

Comment editor functions are cross-wired:
- Click on a main comment form, and upload an image.
- Open an edit comment form and upload an image.
- **Expected Behavior:** The image link should go into the edit comment form.
- **Actual Behavior:** Instead, the image link ends up in the main comment form _(see image)_. The image upload was 'cross-wired' into the main comment form.

103166998-428f5900-47dc-11eb-9441-b46ecf6af58a

## `Why This Happens`
The JS scripts in `/views/comments/_edit.html.erb` and `/app/assets/dragdrop.js` have variables like `$D.selected` and `$E.textarea` that point toward the comment form that the user last interacted with. However, these are often pointing to the wrong form. They need to be updated every time the user takes particular actions: (toggling a form open, entering text, uploading an image).

## `Comment Forms: Uploading Images`
Edit Comment

- **A**: This `div.dropzone` wraps an `input#fileinput`.
  - The user can drag-and-drop (yes, on this tiny area) an image to upload it to the comment, triggering [this 'drop' eventListener in dragdrop.js](https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/app/assets/javascripts/dragdrop.js#L34-L38), then running [this start upload listener here](https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/app/assets/javascripts/dragdrop.js#L53-L62).
  - The user can also just click the button, skipping the 'drop' listener, and going straight to the 'start'.
- **B**: This entire section is wrapped in a `div#c1234div`.
  - The user can drag-and-drop images for upload here.
    - On edit comment forms, this triggers [embedded JS here](https://github.com/publiclab/plots2/blob/9c409ec6bee43b95dfe52191cb5069f4199a4524/app/views/comments/_edit.html.erb#L67-L86) to handle the upload.
    - On main comment forms (at the bottom of the page), and reply forms, this will trigger the code in `dragdrop.js` mentioned above.
- **C**: There's another `input#fileinput` here, similar to the one above but distinct.
  - The user can click here to select an image for upload, which like the one above skips 'drop' event handlers, and goes straight to jQuery's fileupload handlers.

## `Why This Matters`
Ideally, we could write code that sets `$D.selected` to the appropriate `textarea` whenever the user takes one of the actions above. To reiterate, `$D.selected` is a kind of place marker for the editor to know where to put the user's changes (an image link, bold text, etc.)

In practice, `$D.selected` would rely on `e.target` from a click or drop event handler. However, logging `e.target` shows that it's often inaccurate. In the example below, I upload an image in comment 22, and `e.target` (and the image upload) points toward comment 7!

Unclosed  div  tag

Potential causes for this:
- multiple `input`s and `div class='dropzone'`s with the same IDs and classes running around. 
- in my other experiments, multiple e.targets will be logged to the console sometimes. so it could also have something to do with the way the event handlers are being written, and how the click event bubbles up through the DOM.

## `Next Steps`
- [x] ~~I committed some changes in #8927 setting unique IDs on all of the elements diagrammed above. I have a feeling that this will solve the problem of `e.target` being inaccurate. Another fix could potentially be rewriting the event handlers so that they're only searching for click or drop events within certain parts of the DOM tree.~~
- [x] Once unique IDs are set up, I should be able to write the eventHandlers to set `$D.selected` whenever a user **clicks to upload images**. **[PR open: #8987]**

---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### PR DESCRIPTION
**Pull request by noi5e**
Fixes #8926

I think the plan I described in the issue above is actually working! `e.target` is now accurate in the `start` `fileupload` functions. which means we can use it to assign `$D.selected`. That means that every time a user successfully uploads a file by clicking on the upload button, there's a much higher likelihood (if not 100%) that it's going to go into the appropriate box.

**Summary:**
- slight refactoring of `dragdrop.js`'s `drop` eventListener
- assign `$D.selected` to `e.target` in `dragdrop.js`'s `start` `fileupload` function
- some refactoring in `editor.js`'s `wrap` and `refresh` methods
- new system tests:
  - IMMEDIATE image CLICK to upload in **REPLY** comment form works 
  - IMMEDIATE image CLICK to upload in **EDIT** comment form works
  - image CLICK to upload into EDIT form isn't CROSS-WIRED with **MAIN** form
  - image CLICK to upload into EDIT form isn't CROSS-WIRED with **REPLY** form

---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### CODE REVIEW

File: app/assets/javascripts/dragdrop.js [hunk 1]
```diff
@@ -33,25 +33,27 @@ jQuery(function() {
   });
   $('.dropzone').on('drop',function(e) {
     // this 'drop' listener is also reused for pages with just one form, ie. /wiki/new
-    $D.selected = $(e.target).closest('div.comment-form-wrapper').eq(0);
+    const closestCommentFormWrapper = e.target.closest('div.comment-form-wrapper'); // this returns null if there is no match
     e.preventDefault();
     let params = {};
```
Comment (noi5e) [inline app/assets/javascripts/dragdrop.js:38]: I rewrote this part for greater readability, using JavaScript's `closest` (as opposed to jQuery's method with the same name).

JavaScript's `closest` returns `null`, whereas jQuery's returns an object. I thought this would be more intuitive.

File: app/assets/javascripts/dragdrop.js [hunk 2]
```diff
@@ -63,6 +65,13 @@ jQuery(function() {
           'nid':$D.nid
         },
         start: function(e) {
+          // 'start' function runs:
+          //   1. when user drag-and-drops image
+          //   2. when user clicks on upload button.
+          // for click-upload-button scenarios, it's important to set $D.selected here, because the 'drop' listener above doesn't run in those:
+          $D.selected = $(e.target).closest('div.comment-form-wrapper');
+          // the above line is redundant in drag & drop, because it's assigned in 'drop' listener too.
+          // on /wiki/new & /wiki/edit, $D.selected will = undefined from this assignment
```
Comment (noi5e) [inline app/assets/javascripts/dragdrop.js:74]: This is a major change: assign `$D.selected` in the `start` upload function.

As a reminder, this function runs on both `click` and `drop` image upload events. It's important to assign `$D.selected` here for `click` events, because the `drop` listener doesn't run for those.

I left a comment in the code about this, but I'm thinking it would be good down the road to not have to assign `$D.selected` twice in a row for `drop` events. Not sure how to do that yet.

File: app/assets/javascripts/editor.js [hunk 3]
```diff
@@ -1,13 +1,16 @@
...
     args = args || {}
+    // title
+    $E.title = $('#title')
+    // textarea
     args['textarea'] = args['textarea'] || 'text-input'
     $E.textarea = $('#'+args['textarea'])
-    $E.title = $('#title')
+    $E.textarea.bind('input propertychange',$E.save)
+    // preview
     args['preview'] = args['preview'] || 'preview'
```
Comment (noi5e) [inline app/assets/javascripts/editor.js:11]: No additions here, just rearranged stuff for greater readability. Sometime soon, I'd like to rewrite this part to use JavaScript ES6's default parameters: `initialize(textarea = 'text-input')`

File: app/assets/javascripts/editor.js [hunk 4]
```diff
@@ -23,24 +26,25 @@ $E = {
...
-          $E.textarea = ($D.selected).find('textarea').eq(0);
-          $E.preview = ($D.selected).find('#preview').eq(0);
-          $E.textarea.bind('input propertychange',$E.save);
-      }
+    // textarea
+    $E.textarea = ($D.selected).find('textarea').eq(0);
+    $E.textarea.bind('input propertychange',$E.save);
+    // preview
+    $E.preview = ($D.selected).find('#preview').eq(0);
   },
```
Comment (noi5e) [inline app/assets/javascripts/editor.js:39]: I didn't think these lines needed to be inside of a conditional checking for `$D.selected` (it made it little less readable). I moved the conditional into `$E.wrap`

File: app/assets/javascripts/editor.js [hunk 5]
```diff
@@ -23,24 +26,25 @@ $E = {
...
   wrap: function(a,b,args) {
-    var isWiki = (window.location + '').includes('wiki');
-    if (!isWiki) this.refresh();
+    // this RegEx is: /wiki/ + any char not "/" + /edit
+    const isWikiCommentPage = (/\/wiki\/[^\/]+\/edit/).test(window.location.pathname);
+    // we don't need to refresh $E's values if we're on a page with a single comment form, ie. /wiki/new or /wiki/edit
+    if (window.location.pathname !== "/wiki/new" && !isWikiCommentPage && $D.selected) {
+      this.refresh();
+    }
     var len = $E.textarea.val().length;
```
Comment (noi5e) [inline app/assets/javascripts/editor.js:48]: This is a pretty big change too. The `(window.location + '').includes('wiki')` part was originally done in #5650 to fix image upload in `/wiki/new` and `/wiki/{wiki name}/edit`... 

Unfortunately this had the side effect of running `refresh` on wiki comments pages (which `include('wiki')` in the `window.location`). I finally figured out this doesn't need to happen, because the `wiki#show` view just loads comments through `note#comments`. This used to make writing system tests more difficult because things ran differently for wiki comments.

The last note is that I'm thinking that `this.refresh();` may not need to be called at all. We could remove it entirely if we assign `$D.selected` in all the right places. But that's for another PR.

File: test/system/comment_test.rb [hunk 6]
```diff
@@ -321,21 +448,11 @@ def get_path(page_type, path)
...
 
     test "#{page_type_string}: edit comment" do
+      nodes(node_name).add_comment({
+        uid: 2,
+        body: comment_text
+      })
       visit get_path(page_type, nodes(node_name).path)
-      # Create a comment
-      main_comment_form =  page.find('h4', text: /Post comment|Post Comment/).find(:xpath, '..') # title text on wikis is 'Post comment'
-      # fill out the comment form
```
Comment (noi5e) [inline test/system/comment_test.rb:327]: I'm trying to prune the system tests bit-by-bit. Every time we post a comment manually where we don't need to do so is extra runtime. Here `node.add_comment` can save some time.

**Review by jywarren — APPROVED** [review]
Looks great! Ready to merge? Thanks!!!

**Comment by noi5e** [comment]
@jywarren Yep, ready to merge!

**Review by sagarpreet-chadha — APPROVED** [review]
Fantastic !!

**Comment by jywarren** [comment]
🎉🎉🎉
