### PR TITLE
fix the bug of traceback error of server on webpage

### LINKED ISSUE #5378: traceback of error from server is shown in webpage
## Description
While working on the issue https://github.com/publiclab/plots2/issues/5327
I found this. 
It showed the traceback of error from server on the webpage. And after I refreshed it, the tag was added.
The gif shows the steps to reproduce it - 

ff

### PR DESCRIPTION
**Pull request by CleverFool77**
Fixes #5378 https://github.com/publiclab/plots2/issues/5404(<=== Add issue number here)

The changes - 
* If the user adds with tag like `with`,then  there won't be a traceback error like earlier
* If the user adds `with:` or `barnstars:` tag, then it won't show the traceback error rather it would show that the power tag can't be empty.
* The tagname is stripped of whitepaces in ends. As for admin, the code doesn't check condition to find username rather adds it directly. So In such cases the whitespace might be added. 

**Before changes**
error

**After changes**
ff

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

Thanks!

### CODE REVIEW

**Comment by CleverFool77** [comment]
Hi @jywarren @gauravano ,
while working on this issue.
I found some bugs, for which I've opened a new issue https://github.com/publiclab/plots2/issues/5404

File: app/controllers/tag_controller.rb [hunk 1]
```diff
@@ -300,7 +300,7 @@ def create
                            body: "@#{current_user.username} awards a #{barnstar_info_link} to #{node.user.name} for their awesome contribution!")
 
         elsif tagname.split(':')[0] == "with"
-          user = User.find_by_username_case_insensitive(tagname.split(':')[1])
+          user = User.find_by_username_case_insensitive(current_user.username)
```
Comment (gauravano) [inline app/controllers/tag_controller.rb]: Power-tag `with:user1` adds user with username `user1` as co-author of the note. So, we want to get their username from tag and so this change is wrong

Comment (CleverFool77) [reply app/controllers/tag_controller.rb]: Ahh!!! I missed out this. Sorry for the wrong change. I'll commit with correct one soon.
Thanks @gauravano

**Comment by CleverFool77** [comment]
Hi @gauravano I've updated the PR as requested. :smile:
Thanks !!!!!

**Comment by CleverFool77** [comment]
@publiclab/plots2-reviewers 
Please Review.
Thanks !!

File: app/controllers/tag_controller.rb [hunk 2]
```diff
@@ -287,25 +287,33 @@ def create
     node = Node.find nid
     tagnames.each do |tagname|
       # this should all be done in the model:
-
+      tagname = tagname.strip
       if Tag.exists?(tagname, nid)
         @output[:errors] << I18n.t('tag_controller.tag_already_exists')
+
+      elsif tagname.include?(":") && tagname.split(':').length < 2 # cant tag empty power tags
```
Comment (gauravano) [inline app/controllers/tag_controller.rb]: You mean `Can't add empty power tags` :sweat_smile: ?

File: app/controllers/tag_controller.rb [hunk 3]
```diff
@@ -287,25 +287,33 @@ def create
...
+        if tagname.split(':')[0] == "barnstar" || tagname.split(':')[0] == "with"
```
Comment (gauravano) [inline app/controllers/tag_controller.rb]: hey @CleverFool77, I think we can implement this for all power tags, we have many - https://publiclab.org/wiki/power-tags. What do you say?

**Comment by gauravano** [comment]
Great work here! @CleverFool77 :100:

File: app/controllers/tag_controller.rb (hunk 2 above)
Comment (CleverFool77) [reply app/controllers/tag_controller.rb]: Hi @gauravano 
What I mean was we can add `with` but not `with:` ? :sweat_smile: 
Is this not supposed to be like this ?

File: app/controllers/tag_controller.rb (hunk 3 above)
Comment (CleverFool77) [reply app/controllers/tag_controller.rb]: Hi @gauravano In other power tags, If I'll add some of the other power tags like `build:`, `alert:` ,`notes:` etc then neither it shows traceback error nor its gets added, which is correct.

Only `with:` and `barnstars:` which were implemented in different way were showing traceback error and That's why I added only both of them here.
Thanks !!!

File: app/controllers/tag_controller.rb (hunk 2 above)
Comment (gauravano) [reply app/controllers/tag_controller.rb]: I was referring to comment not code :sweat_smile:

File: app/controllers/tag_controller.rb (hunk 3 above)
Comment (gauravano) [reply app/controllers/tag_controller.rb]: Ok! I think, we can discuss it after merging this that whether we want to show alert if someone try to use incomplete power tag, even in case where no error is thrown. Thanks!

**Comment by gauravano** [comment]
I think, we are almost done here. Just correct the comment or you can also remove it. Thanks!

File: app/controllers/tag_controller.rb (hunk 2 above)
Comment (CleverFool77) [reply app/controllers/tag_controller.rb]: Ahh!! Forgot about that. I'll fix it.

**Comment by CleverFool77** [comment]
Hi @gauravano 
I've updated the PR.
Thanks !!

**Comment by gauravano** [comment]
:tada: :100: :+1:
