### PR TITLE
contributor count on tags page fixed

### LINKED ISSUE #2042: List wiki revision authors as contributors on /contributors/tagname pages
### Please describe the problem (or idea)

I noticed that "Nova" just contributed a revision to the water sensors wiki page: https://publiclab.org/water-sensors

However, they don't appear on the contributors page for that tag: https://publiclab.org/contributors/water-sensors

How hard would it be to add all revision authors to that query? 

https://github.com/publiclab/plots2/blob/5bd6efacc416dc2a1b1235b386c44babe8602b72/app/controllers/tag_controller.rb#L315-L325

Could we make an implementation closer to how `contributor_count` works, in the Tag model?

https://github.com/publiclab/plots2/blob/5bd6efacc416dc2a1b1235b386c44babe8602b72/app/models/tag.rb#L55-L66

Could this implementation also live in the Tag model, and even use the same code as `contributor_count`?

Any help appreciated!

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2042

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
@jywarren please see if this solves the problem!

File: app/controllers/tag_controller.rb [hunk 1]
```diff
@@ -321,7 +321,7 @@ def contributors
                  .references(:term_data, :node_revisions)
                  .where('term_data.name = ?', params[:id])
                  .order('node_revisions.timestamp DESC')
-    @users = @notes.collect(&:author).uniq
+    @users = DrupalUser.where(uid: Tag.contributors(@tagnames[0]))
```
Comment (jywarren) [inline app/controllers/tag_controller.rb]: Is it possible to use `User.where(id: ...` here instead, since we're trying to stop using DrupalUsers? Thank you! This otherwise looks fantastic.

File: app/models/tag.rb [hunk 2]
```diff
@@ -52,8 +52,9 @@ def belongs_to(current_user, nid)
     node_tag && node_tag.uid == current_user.uid || node_tag.node.uid == current_user.uid
   end
 
-  def self.contributor_count(tagname)
+  def self.contributors(tagname)
```
Comment (jywarren) [inline app/models/tag.rb]: Love this!!! 👍 👍

File: app/controllers/tag_controller.rb (hunk 1 above)
Comment (ViditChitkara) [reply app/controllers/tag_controller.rb]: Hi, I guess we'd have to refactor the Tag.contributors method then, which currently  gives  array of uid (drupal_user id)!! Let's give it a try.

Comment (ViditChitkara) [reply app/controllers/tag_controller.rb]: @jywarren I guess we need to write a conversion function in user mode which fetches user_ids against drupal_user_ids. Then we could replace the DrupalUser with User in L324. Do you think this is the correct way, however it doesn't completely rules out DrupalUser.
The function would look something like (Would go in User Model):-
```
def self.user_ids(drupal_user_ids)
  user_ids=[]
  drupal_users = DrupalUser.include(:user).where(uid: drupal_user_ids)
  drupal_users.each do |du|
    user_ids<<du.user.id
  end
end
```
This would greatly increase the overload time since a separate query is required to fetch a user from drupal_user. Do you think we should do this???

Comment (jywarren) [reply app/controllers/tag_controller.rb]: So, we've synced `User.id` and `DrupalUser.uid` and you can treat one like the other -- we did a big database migration a while back to ensure this. Does that help?

**Comment by ViditChitkara** [comment]
Sure, I'll do!

**Comment by ViditChitkara** [comment]
Done with the tests!

File: app/models/tag.rb [hunk 3]
```diff
@@ -62,6 +63,11 @@ def self.contributor_count(tagname)
       uids+=n.revision.collect(&:uid)
     end
     uids = uids.uniq
+    uids
```
Comment (jywarren) [inline app/models/tag.rb]: Ah, so, do you think we should return an ActiveRecord collection here, instead of just uids? Like, replace this line with `User.find uids` instead -- and then the line above (https://github.com/publiclab/plots2/pull/2055/files#diff-a8eb2425ebeb0814d010864bb014e815R326) would be simpler -- make sense?

Comment (ViditChitkara) [reply app/models/tag.rb]: Yes, makes sense, will do!!

File: app/views/tag/contributors.html.erb [hunk 4]
```diff
@@ -68,7 +68,7 @@
 
   <% end %>
 
-  <% if @notes.nil? || @notes.length == 0 %>
+  <% if @users.nil? || @users.length == 0 %>
```
Comment (ViditChitkara) [inline app/views/tag/contributors.html.erb]: Found some unexpected behaviour when @notes.length was 0 but @users still existed hence modified the condition a bit!!

File: app/models/tag.rb (hunk 3 above)
Comment (ViditChitkara) [reply app/models/tag.rb]: @jywarren done with the suggested changes!

**Comment by jywarren** [comment]
Super, is this ready to go, then? Thanks!

**Comment by ViditChitkara** [comment]
Yes!!

**Comment by jywarren** [comment]
Awesome!
