### PR TITLE
Corrected links in header

### LINKED ISSUE #9964: Incorrect links in navbar section for tools
Some of the links in the navbar section for `Tools` lead to an error page.

### PR DESCRIPTION
**Pull request by anirudhprabhakaran3**
Fixes #9964  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by anirudhprabhakaran3** [comment]
I've made the change based on the link format that was used for store.publiclab.org, which seems to work. Hoping that the same format for these links will also work.

**Comment by jywarren** [comment]
Actually i think the issue is here! 

https://github.com/publiclab/plots2/blob/d092648e4698fbbd49a4531b36b83e94703d83f3/app/helpers/application_helper.rb#L174-L176

I'm going to try modifying that too. We can keep your changes as well, they're fine!

File: app/helpers/application_helper.rb [hunk 1]
```diff
@@ -171,9 +171,9 @@ def translation(key, options = {}, html = true)
   def create_nav_dropdown_item(href, text)
     translated_string = translation(text)
     if current_user&.has_tag('translation-helper') && I18n.locale != :en
-      raw(%(<div class="dropdown-item"> <a class="text-body" href="/#{href}"> #{translated_string}</a> </div>))
+      raw(%(<div class="dropdown-item"> <a class="text-body" href="#{href}"> #{translated_string}</a> </div>))
```
Comment (jywarren) [inline app/helpers/application_helper.rb:174]: see this change and on line 176

File: app/views/layouts/_header.html.erb [hunk 2]
```diff
@@ -43,12 +43,12 @@
               <a class="dropdown-item" href="/getting-started"><b><%= translation('layout._header.community.get_started') %> &raquo;</b></a>
             <% end %>
               <div class="dropdown-divider"></div>
-              <%= create_nav_dropdown_item("people","layout._header.community.people") %>
-              <%= create_nav_dropdown_item("map","layout._header.community.places") %>
-              <%= create_nav_dropdown_item("projects","layout._header.community.projects") %>
-              <%= create_nav_dropdown_item("events","layout._header.community.events") %>
-              <%= create_nav_dropdown_item("questions","layout._header.community.questions") %>
-              <%= create_nav_dropdown_item("chat","layout._header.community.chat") %>
+              <%= create_nav_dropdown_item("/people","layout._header.community.people") %>
```
Comment (jywarren) [inline app/views/layouts/_header.html.erb:46]: and on every instance of the use of this helper. Should work!

**Review by jywarren — APPROVED** [review]

File: app/views/layouts/_header.html.erb (hunk 2 above)
Comment (anirudhprabhakaran3) [reply app/views/layouts/_header.html.erb:46]: Aah yes, I got it. Thanks for pointing this out! This is a much elegant way.

I guess then for the external site URLs, we can use the https:// URLs now, right? Since it won't cause a problem now, and having the // in the URL seems improper.
