### PR TITLE
Tag sort defaults

### LINKED ISSUE #8941: /tags is (wrongly) alphabetically sorted...? need to better define defaults to see if there are issues
https://publiclab.org/tags?sort=followers&order=asc doesn't seem to sort by # of uses - 

do wiki edits/tags bump these up, or count?

what if we show wiki count?

Possibly related to https://github.com/publiclab/plots2/pull/8935 cc @RuthNjeri

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #8941  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

File: app/controllers/tag_controller.rb [hunk 1]
```diff
@@ -8,7 +8,8 @@ def index
 
     @title = I18n.t('tag_controller.tags')
     @paginated = true
-    @order_type = params[:order].blank? || params[:order] == "desc" ? "asc" : "desc"
+    @order_type = params[:order].blank? || (params[:order] == "desc") ? "desc" : "asc"
```
Comment (jywarren) [inline app/controllers/tag_controller.rb:11]: Hmm, what's the difference between `order_type` and `order_name`? or should `order_name` be like, `name`, `followers` etc?

Comment (jywarren) [reply app/controllers/tag_controller.rb:11]: Maybe we need more specific variable names here...

**Comment by jywarren** [comment]
Should we also just be changing the links shown on the page so the initial ones are correctly ordered? Or are we just changing the meaning of omitting the sort order as a param, so... oh, i see; we actually preset them with Ruby variables anyways:

https://github.com/cesswairimu/plots2/blob/47a7ab0af115b1cd38ac44915b34770c74975c52/app/views/tag/index.html.erb#L23-L26

File: app/controllers/tag_controller.rb (hunk 1 above)
Comment (cesswairimu) [reply app/controllers/tag_controller.rb:11]: `order_name` will be the order by  for 'names' so that we can default it to 'asc', while `order_type` will be used for 'uses' and  'followers for these we will default to 'desc' as we discussed...maybe i can use a better name `order_for_name` maybe?

**Comment by cesswairimu** [comment]
The links default links are okay now they are reading from the controller, if not set `uses and `followers` are ordered `desc` and `names` as `asc`

**Comment by cesswairimu** [comment]
@jywarren changed `order_name` to `order_type_for_name`  better?

**Comment by jywarren** [comment]
Sure but... does it have to be a separate variable at all? I'm totally ok with it if there's a good reason, just wasn't sure. Thanks so much, Cess!

**Comment by cesswairimu** [comment]
Yeah we need a different variable for asc ordering...since `order_type`. default is desc

**Comment by jywarren** [comment]
OK, awesome, sounds good! Merged!
