### PR TITLE
comments on profile page fixed

### LINKED ISSUE #2196: Comments not loading on certain profile pages
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

Unable to fetch comments for certain profile pages (e.g: https://publiclab.org/profile/liz, https://publiclab.org/profile/warren). 
comments-1-1

### Please show us where to look

https://publiclab.org/profile/liz, https://publiclab.org/profile/warren (click on the comments tab)

### What's your PublicLab.org username?

vidit

### PR DESCRIPTION
**Pull request by ViditChitkara**
fixes #2196

Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!

* [X] all tests pass -- `rake test:all`
* [X] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X] pull request is descriptively named with #number reference back to original issue

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/wiki/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.

Thanks!

### CODE REVIEW

**Comment by ViditChitkara** [comment]
@jywarren could you have a look at it?

File: app/models/comment.rb [hunk 1]
```diff
@@ -5,8 +5,8 @@ class Comment < ActiveRecord::Base
     :subject, :hostname, :comment,
     :status, :format, :thread, :timestamp
 
-  belongs_to :node, foreign_key: 'nid', touch: true,
-                    dependent: :destroy, counter_cache: true
+  belongs_to :node, foreign_key: 'nid', touch: true, counter_cache: true
```
Comment (jywarren) [inline app/models/comment.rb]: Hmm, does this have to do with the comment changes? What was the issue? I wasn't sure `counter_cache` was working and would like to demonstrate this with a test if that's OK... a unit test?

File: app/models/comment.rb [hunk 2]
```diff
@@ -67,7 +67,7 @@ def parent
     if aid == 0
       node
     else
-      answer.node
+      answer && answer.node
```
Comment (jywarren) [inline app/models/comment.rb]: Here, we have to be careful because `parent` should return the record, not just a boolean. Can you think of how to split this out more clearly? Or maybe we make an alternate way to refer to an answer instead of the parent node?

File: app/models/comment.rb (hunk 1 above)
Comment (ViditChitkara) [reply app/models/comment.rb]: Hi @jywarren. Actually I haven't removed counter_cache but 'dependent: :destroy'.
Actually the error was occurring because some comments did not belong to an answer or a node. Perhaps there is no need of dependent: :destroy here but the node model (has_many comments, dependent: :destroy). Just realized that dependent destroy also needs to be added to answer model here:-
https://github.com/publiclab/plots2/blob/b978d2bd8912a3c4cbffd3a320f44f05deb8764d/app/models/answer.rb#L9
Please correct me if I am wrong!

File: app/models/comment.rb (hunk 2 above)
Comment (ViditChitkara) [reply app/models/comment.rb]: Oops, my mistake, you're right. I just need to check if answer existed then return answer.node

Comment (ViditChitkara) [reply app/models/comment.rb]: I'll make the changes right away!

**Comment by ViditChitkara** [comment]
@jywarren thanks for the review!! I,m writing the tests now along with minor tweaks.

File: app/models/comment.rb (hunk 1 above)
Comment (ViditChitkara) [reply app/models/comment.rb]: Hi @jywarren , The tests are written. Please have a look

File: app/controllers/answers_controller.rb [hunk 3]
```diff
@@ -41,7 +41,7 @@ def delete
        current_user.role == 'admin' ||
        current_user.role == 'moderator'
       respond_to do |format|
-        if @answer.delete
+        if @answer.destroy
```
Comment (ViditChitkara) [inline app/controllers/answers_controller.rb]: destroy method triggers dependent: :destroy callback, hence, delete was changed to destroy here.

File: app/controllers/notes_controller.rb [hunk 4]
```diff
@@ -233,7 +233,7 @@ def update
   def delete
     @node = Node.find(params[:id])
     if current_user.uid == @node.uid && @node.type == 'note' || current_user.role == 'admin' || current_user.role == 'moderator'
-      @node.delete
+      @node.destroy
```
Comment (ViditChitkara) [inline app/controllers/notes_controller.rb]: Same as answer_controller

**Comment by jywarren** [comment]
Awesome! Great work here.
