### PR TITLE
Scroll top fix @publiclab

### LINKED ISSUE #6435: Remove "scroll to top" arrow key
Please Note:  **We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more**

### Problem

We can find that the scroll-to-top arrow key also appears when we are at the top of the page.
[here](https://publiclab.org/) 

Screenshot (21)_LI

hence, we should add some javascript scroll function so that it becomes visible only when the user starts to scroll the page

### PR DESCRIPTION
**Pull request by Asiedu13**
Fixes #6435  (<=== Add issue number here)
Please review or comment@publiclab
Thanks!

### CODE REVIEW

File: scroll-func.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+let scrollBtn = document.querySelector(".back-to-top");
+window.addEventListener("scroll", function(){
+      let position = window.scrollY;
```
Comment (seabl) [inline scroll-func.js]: @Asiedu13 Could you fix the indentations please, and make them uniform.

Comment (Asiedu13) [reply scroll-func.js]: Sure

**Comment by IshaGupta18** [comment]
This looks good! @jywarren @SidharthBansal please merge it if you find it okay!

**Comment by cesswairimu** [comment]
Hi all, is the scrollbar ever visible locally? I pulled the changes and could not see it...Thanks all

**Comment by anthony-zhou** [comment]
@Asiedu13 Please see my comment on PR #6942 for some tips on integrating this script so that it can be used on the site and seen locally. Thanks!

**Comment by SidharthBansal** [comment]
Can we merge this @cesswairimu

**Comment by cesswairimu** [comment]
Yes we can

**Comment by cesswairimu** [comment]
Thanks everyone

**Comment by SidharthBansal** [comment]
Thanks all

File: scroll-func.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+      if(position < 200){
+      scrollBtn.style.opacity = "0";
```
Comment (frappelatte28) [inline scroll-func.js:5]: @cesswairimu should not we use "visibility=hidden" instead of "opacity=0" as in this case we still are able to interact with the "scrollBtn"

Comment (cesswairimu) [reply scroll-func.js:5]: @frappelatte28 I thought the two are the same...but I am not the best at styling :laughing: ...would you like to give it a shot and open a PR with the visibility option, see how it goes?
