### PR TITLE
topic card count fixes for #7965

### LINKED ISSUE #7965: Remove "-" before count of posts on Topic Cards when sorting by "# of People"
### Please describe the problem

There appears to be a tiny "-" before the count of posts on Topic Cards when the "# of People" sorting option is clicked, making it appear like there is a negative count of posts. See screenshot: 

Screen Shot 2020-05-20 at 10 36 42 AM (1)

> What did you expect to see that you didn't?

i expected to see positive integers. 

### Please show us where to look

https://publiclab.org/tags?sort=followers&order=asc

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

### PR DESCRIPTION
**Pull request by jywarren**
Fixes #7965, supercedes #8048

### CODE REVIEW

File: app/models/node_tag.rb [hunk 1]
```diff
@@ -8,13 +8,11 @@ class NodeTag < ApplicationRecord
   has_many :tag_selections, foreign_key: 'tid'
   accepts_nested_attributes_for :tag
 
-  after_create :increment_count
+  after_create :update_count
```
Comment (jywarren) [inline app/models/node_tag.rb:11]: Adding better updaters for tag counting

**Comment by jywarren** [comment]
Also testing this out at http://unstable.publiclab.org/tags, where I just pushed it!

File: app/views/tag/_topicCard.html.erb [hunk 2]
```diff
@@ -32,7 +32,7 @@
       </div>
 
       <div class="card-footer" style="background-color: inherit; border:none;">
-        <a style="padding-top:15px;text-decoration:underline;color:#808080;display:inline-block;" href="/tag/<%= tag.name %>"><%= Tag.counter(tag.name)-shown_nids.count - Tag.find_nodes_by_type(tag.name, type = 'note', limit = 3).where.not(nid: shown_nids).count %> <%= translation('tag.index.more_posts') %> &raquo;</a>
+        <a style="padding-top:15px;text-decoration:underline;color:#808080;display:inline-block;" href="/tag/<%= tag.name %>"><%= Tag.count %> <%= translation('tag.index.posts') %> &raquo;</a>
```
Comment (jywarren) [inline app/views/tag/_topicCard.html.erb:35]: Oops, it should've been `tag.count` not `Tag.count` -- fixing in follow-up!!!

**Comment by jywarren** [comment]
MISTAKE! See last comment, follow-up in https://github.com/publiclab/plots2/commit/af6083a1e15483c59aeb0dce343cf4b163aba150

**Comment by jywarren** [comment]
Let's confirm in https://stable.publiclab.org/tags -- 😅
