### PR TITLE
Fix toggle_preview() by removing code that is grabbing non-existing ids

### LINKED ISSUE #3691: "Preview" for new posts not opening in Firefox and Chrome
I've noticed that the "preview" option hasn't been working for new wikis and research notes for at least the past few days. 

The editor seems to be working properly otherwise, but pressing the button doesn't open up a new view. 

preview

### PR DESCRIPTION
**Pull request by amychan331**
Fixes #3691

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Comment by amychan331** [comment]
@jywarren Turns out that in issue #3546, 'id' argument was added for toggle_preview(). It works specifically for comment/_form.html.erb - and breaks every other pages that uses toggle_preview(). All it takes to toggle preview button is adding a preview-btn class and data-previewing-text attribute. id was never needed. So I have fixed the comment/_form.html.erb file into using the way other pages are done. No change is needed in wiki or research note page.

Not sure if this should be in the same pull request, but something else I notice:
The data-previewing-text's value of "Previewing (click to edit)" confused me since I can clearly edit while previewing. Then I realize $(#dropzone) is suppose to be grabbing the .dropzone class, not id. Do you want that fix or just remove $(#dropzone).toggle all together?

**Comment by jywarren** [comment]
Hmm, I think best to toggle off the textarea while previewing... I think
it's been broken like that for a while! Thanks for this great fix!!!!

**Comment by amychan331** [comment]
Done! The textarea, AKA .dropzone, now toggles when previewing mode is on.

**Comment by gauravano** [comment]
Hi @amychan331, I was trying the changes and got this output:

https://drive.google.com/open?id=11voAGrQLB3Mx_b7U37qk9gR2rfwPy41f

The button is working but the preview output is displayed at the wrong place(comment). Hope it helps in debugging!

File: app/assets/javascripts/editor.js [hunk 1]
```diff
@@ -105,16 +105,15 @@ $E = {
   generate_preview: function(id,text) {
     $('#'+id)[0].innerHTML = marked(text)
   },
-  toggle_preview: function(id) {
+  toggle_preview: function() {
     $E.preview[0].innerHTML = marked($E.textarea.val());
```
Comment (gauravano) [inline app/assets/javascripts/editor.js]: `$E.preview[0]` this is probably targetting 1st comment, it works in case of Notes as Notes have just 1 comment form at the end, but in case of Question, there would be comment form with each answer.

**Comment by amychan331** [comment]
For the blog page with multiple comments possible, the code behind toggling the new comment and for toggling a existing comment is different - first one came from the app/assets/javascripts/editor.js file, and the later is mostly inline inside app/views/comments/_edit.html.erb. The code behind the new comment (inside editor.js) is also used for creating new wiki and new research notes inside the legacy editor.
For the toggle_preview() inside editor.js, I set the argument with a default value of null, so it would work with or without argument pass.
Everything else is just trying to define a more precise selector, so it doesn't grab wrong div or class when there are multiple comments in the page.
Here is the blog page with multiple comments:
comments_page
Here is the page to create new wikis
new_wiki
Here is the page to create new research notes in legacy editor (the new one don't have preview):
legacy_research_note

**Comment by amychan331** [comment]
Sorry, accidentally clicked on "Close and comment" - for some reason I thought it was "Preview" button! Probably cause I was working the bottom right preview button so much in the blog page comments...

**Comment by jywarren** [comment]
Oh goodness, this is overdue for review, my apologies! Will look at this shortly, i am reviewing Outreachy proposals now. Sorry about this!

**Comment by amychan331** [comment]
@jywarren First time doing git rebase. Hope everything is done correctly! After rebasing, I noticed the updated code have an extra pair of script tag that was causing loading error, so I removed those too.  If anyone had problem publishing earlier, that may be it.

**Comment by amychan331** [comment]
@jywarren Another git rebase since there has been changes that cause conflict in the last 7 days.......

**Comment by jywarren** [comment]
This is PERFECT! Thank you!!! Fantastic work, and kudos for becoming a rebasing expert 👍 🎉
