### PR TITLE
Bug: Show Image Upload Progress Bars in Edit Comment CLICK-to-Upload

### LINKED ISSUE #9018: Bug: Progress Bars Don't Show for Edit Comment CLICK-to-Upload Image
**Steps to Reproduce:**
1. Open up an edit comment form.
2. Upload an image by clicking on the button in the toolbar.
3. The rich-text image link does appear in the correct form.
4. However, even though the upload proceeds correctly, the progress bars don't show.

[Video Showing Buggy Behavior, and Ideal Behavior](https://user-images.githubusercontent.com/4361605/104821473-f50d7700-57f0-11eb-950d-13d21894500c.mov)

This bug occurs because the toolbar button in edit comment forms call on a `fileupload` method in `dragdrop.js`. The CSS selectors in this method refer to elements that exist in reply and main comment forms, but that **DON'T** exist in edit comment forms:
https://github.com/publiclab/plots2/blob/a3c87969663f482432cd4cbb43b95cd70726bfd4/app/assets/javascripts/dragdrop.js#L78-L82

Here's how they are in edit comment forms:
https://github.com/publiclab/plots2/blob/a3c87969663f482432cd4cbb43b95cd70726bfd4/app/views/comments/_edit.html.erb#L17-L28

As opposed to reply and main comment forms:
https://github.com/publiclab/plots2/blob/a3c87969663f482432cd4cbb43b95cd70726bfd4/app/views/comments/_form.html.erb#L64-L75

Going to take care of this bug in stages:
- [x] Write system tests.
- [x] Add unique IDs and common classes to progress bar elements.
- [x] Change scripts to refer to the common class, ie. `.progress` instead of `#create_upload`.

I think this bugfix will pave the way for combining the scripts for edit comment forms with scripts for reply/main comment forms... They're so similar, it would really be helpful if they were just consolidated.

---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### PR DESCRIPTION
**Pull request by noi5e**
Fixes #9018 (see this issue page for a more detailed write-up & game plan)

This fixes the original bug **AND** I made a few extra changes to image upload CSS:
- reset `.progress-bar`'s CSS width to 0 after a fileupload, so it can be reused for a second upload.
- `hover` class was not appearing (the div wasn't darkening) when user hovered an image over the `.dropzone`.
- changed EDIT comment form's progress bar to be stripy, and animated.

[Before Fixes](https://user-images.githubusercontent.com/4361605/104832454-0339b280-5846-11eb-83af-d60a757c66f3.mov)
[After Fixes](https://user-images.githubusercontent.com/4361605/104832462-1c426380-5846-11eb-9d4c-56b55fae1f4c.mov)
- div darkens on hover, then resets on dragout
- upload bar resets to 0

---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

### CODE REVIEW

File: app/assets/javascripts/dragdrop.js [hunk 1]
```diff
@@ -17,44 +17,36 @@ jQuery(function() {
     );
   }
 
-  $('.dropzone').on('dragover',function(e) {
-    e.preventDefault();
```
Comment (noi5e) [inline app/assets/javascripts/dragdrop.js:21]: I stuck these listeners in the `$('.dropzone').each` further down. Having them inside that function lets me use `$(this)` to attach an eventListener... Which reduces the number of times that the same eventListener is attached to the same element.

File: app/assets/javascripts/dragdrop.js [hunk 2]
```diff
@@ -17,44 +17,36 @@ jQuery(function() {
...
-  });
-
   // these functions are also used on /wiki/edit and /wiki/new pages
   $('.dropzone').each(function() {
+    $(this).on('dragenter',function(e) {
+      e.preventDefault();
+      $(e.currentTarget).addClass('hover');
+    });
+
```
Comment (noi5e) [inline app/assets/javascripts/dragdrop.js:26]: Changed `dragover` and `dragout` to `dragenter` and `dragleave` so they don't fire every time the user makes a movement with the image on the surface of the div.

File: app/assets/stylesheets/editor.css [hunk 3]
```diff
@@ -32,17 +32,17 @@ pre {
...
   code {
-    padding: 0;
+    padding: 0px;
     font-size: inherit;
     color: inherit;
     white-space: pre-wrap;
     background-color: transparent;
     border-radius: 0;
   }
-}
```
Comment (noi5e) [inline app/assets/stylesheets/editor.css:46]: I believe this was an extra close curly-brace that may have been affecting the CSS! Also fixed the commenting before this block.

File: app/assets/stylesheets/question.css [hunk 4]
```diff
@@ -118,7 +118,6 @@ table th a:hover {
   visibility: hidden;
 }
 
-.question-show textarea,
 .question-show pre {
   margin: 0;
```
Comment (noi5e) [inline app/assets/stylesheets/question.css:122]: I removed this CSS reference to fix a styling issue in Edit Comment forms. I believe this was done originally to fix #1304, which I think was for the `publiclab.org/questions` route, so unrelated to comments on questions.

This is what the Edit Comment looked like before this change (no border color, no padding):
Screen Shot 2021-01-16 at 9 34 27 PM

This is what it looks like after this fix:
Edit Comment After CSS Fix

File: app/views/comments/_edit.html.erb [hunk 5]
```diff
@@ -39,10 +39,6 @@
       </div>
     </div>
       <script type="application/javascript">
-        jQuery(document).ready(function() {
-          $E.initialize();
-        });
-
         function setInit(id) {
```
Comment (noi5e) [inline app/views/comments/_edit.html.erb:42]: I removed this `$E.initialize` call, I think it's unnecessary because it's already done in so many other places on a page with comments.

**Comment by noi5e** [comment]
@jywarren Okay, ready to merge!

**Review by Sagarpreet — APPROVED** [review]
This is awesome 🎉 
I think a better approach to find the `divs` or anything inside a comment editor would be the direct use of `id`'s, like instead of trying to find the closest DOM element inside form like:
`e.target.closest('div.comment-form-wrapper');`
It would be better to access it directly like:
`comment-form-wrapper-2131` where `2131` is some unique id.
Advantage being we are sure that even if their are multiple forms, we are always manipulating the correct DOM elements.
Saying that, the current approach is also fine for now 😄

File: app/assets/javascripts/dragdrop.js [hunk 6]
```diff
@@ -115,15 +102,27 @@ jQuery(function() {
         },
 
         // see callbacks at https://github.com/blueimp/jQuery-File-Upload/wiki/Options
-        fileuploadfail: function(e,data) {
+        // fileuploadfail: function(e,data) {
```
[the remark this answers is not in the document]
Comment (noi5e) [reply app/assets/javascripts/dragdrop.js:95]: That's a good idea, can do it in a follow-up PR

**Comment by noi5e** [comment]
@Sagarpreet Thanks for the detailed review! I just resolved the merge conflict, and tests are passing, so this one's ready to merge again. @jywarren @cesswairimu 

I totally agree about referring to comment forms with a unique ID rather than `div.comment-form-wrapper`. I put it on my to-do list. I'm starting to refactor a lot of the code this week, so I hope to make some progress on implementing that.

**Review by jywarren — APPROVED** [review]
This looks amazing, i appreciate all the small and careful tweaks, fixes, and documentation. it was easy to read and review and @Sagarpreet's review is also super helpful, thanks!

Approving and merging!!!
