### PR TITLE
Fixes #7831. Fixed filter spam tags in app/controllers/stats_controller.rb

### LINKED ISSUE #7831: Filter spam tags from /stats/subscriptions
@ebarry reports:

> Not urgent, but there are many spammy tags that have already been deleted from publiclab.org pages that are still showing up in the "0-9" subscriptions area of this page: https://publiclab.org/stats/subscriptions

We can edit the stats controller so that only tags that have at least one published node attached are displayed.

More in a moment (github outage!)

Here is the controller where we collect the tags:

https://github.com/publiclab/plots2/blob/4f68d273c9cf1526ddd65ec059e81401d08bf73a/app/controllers/stats_controller.rb#L2-L9

I think we can just add `.joins(:node)` ? If so this could be a FTO...!

https://github.com/publiclab/plots2/blob/4f68d273c9cf1526ddd65ec059e81401d08bf73a/app/models/tag.rb#L398

It may need to be `.joins(:tag, :node)` ? This can be tested on the rails console.

### PR DESCRIPTION
**Pull request by dongskyler**
Fixes #7831.  (<=== Add issue number here)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

@cesswairimu

Thanks!

### CODE REVIEW

File: app/controllers/stats_controller.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 class StatsController < ApplicationController
   def subscriptions
     @tags = {}
-    TagSelection.where(following: true).each do |tag|
+    TagSelection.joins(:node_tags).where(following: true).each do |tag|
```
Comment (cesswairimu) [inline app/controllers/stats_controller.rb:4]: Thanks for working on this so quick @dongskyler :tada:  ...we want this to become `TagSelection.where(following: true)        .joins(:node_tags)` as explained in this comment https://github.com/publiclab/plots2/issues/7831#issuecomment-620770359

Comment (dongskyler) [reply app/controllers/stats_controller.rb:4]: I’m happy to work on it shortly. 

But to be clear, this calls for another branch and another PR, and it will void my previous PR. This was not what I modified in my previous branch.

Comment (cesswairimu) [reply app/controllers/stats_controller.rb:4]: Not really...we are moving the 'join' after the 'where'..
in the previous PR we had `TagSelection.joins(:node_tags).where(following: true)` and before that we did not have the joins to node_tags

Comment (dongskyler) [reply app/controllers/stats_controller.rb]: I misunderstood what you instructed me to do.

I have updated the branch and both tests have passed.

Please review.

**Comment by cesswairimu** [comment]
hey, I can't see the changes on the files changes maybe you deleted that commit..kindly check. Thanks

**Comment by dongskyler** [comment]
> hey, I can't see the changes on the files changes maybe you deleted that commit..kindly check. Thanks

I'm sorry I didn't fix the issue right away.

**Comment by cesswairimu** [comment]
No worries...thanks for woking on this @dongskyler
