### PR TITLE
Fix #5418: Fixed counter in comment section in notes

### LINKED ISSUE #5418: improve comment section in notes
when we click on publish button in the comment But the comment is blank and the total comment is count But after refresh page is working fine. more can see in the gif below
pub7

thank you : )

### PR DESCRIPTION
**Pull request by ValeriaCobianISW**
Fixes #5418
PR5418

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

File: app/assets/javascripts/comment.js [hunk 1]
```diff
@@ -6,7 +6,6 @@
         $(this).find('#text-input').prop('disabled',false);
         $(this).find('#text-input').val('');
         $('#comments-container').append(xhr.responseText);
-        $('#comment-count')[0].innerHTML = parseInt($('#comment-count')[0].innerHTML, 10)+1;
```
Comment (gauravano) [inline app/assets/javascripts/comment.js]: Removing this solves the issue but how the control is coming here as comment is not added?

Comment (ValeriaCobianISW) [reply app/assets/javascripts/comment.js]: I can add a validation to verify when the comment isn't added and display an error, I'm going to add that :+1: 
Thank you @gauravano

Comment (ValeriaCobianISW) [reply app/assets/javascripts/comment.js]: Should I add a new issue for this? @gauravano

Comment (gauravano) [reply app/assets/javascripts/comment.js]: Actually, let's put a Javascript condition to disable the button if the comment body is empty. How does it sound?

Also, sorry for delay here.

Comment (gauravano) [reply app/assets/javascripts/comment.js]: @ValeriaCobianISW regarding showing the error message in case of failure, we already have that but it needs some fix. Like, I tested commenting the empty body on production and count increased but when I went to dashboard this alert appeared 

Screenshot from 2019-04-30 17-37-42

may be we need to change it to flash.now or something. Would you like to fix this too?

Thanks!

**Comment by gauravano** [comment]
Merged :tada: :+1:.

File: app/assets/javascripts/comment.js (hunk 1 above)
Comment (ValeriaCobianISW) [reply app/assets/javascripts/comment.js]: Sure, I would like to fix it, I'm going to open a new issue and work on it, thank you @gauravano :D
