### PR TITLE
Fixed username error

### LINKED ISSUE #9421: ActionView::Template::Error: undefined method `username' for nil:NilClass
Sentry Issue: [PLOTS2-18G](https://sentry.io/organizations/publiclab/issues/2311402384/?referrer=github_integration)

This seems to affect visiting the wiki root path at https://publiclab.org/wiki/, but may interact with being redirected to the https://publiclab.org/join/ path?

```
NoMethodError: undefined method `username' for nil:NilClass
  app/views/wiki/_header.html.erb:37:
    <li style='list-style: none;'><a href='/profile/<%= author.username %>' style='color: #009bff;'>@<%= author.username %></a></li>
  app/views/wiki/_header.html.erb:36:in `each'
    <% @node.authors.each do |author| %>
  app/views/wiki/_header.html.erb:36:
    <% @node.authors.each do |author| %>
  app/views/wiki/show.html.erb:25:
    <%= render partial: "wiki/header" %>
  app/controllers/wiki_controller.rb:269:in `root'
    render template: 'wiki/show'
...
(158 additional frame(s) were not displayed)

ActionView::Template::Error: undefined method `username' for nil:NilClass
```

### PR DESCRIPTION
**Pull request by gaurav2699**
Fixes #9421 (<=== Add issue number here)]
Screenshots: 
This wiki doesnt have a user associated
Screenshot from 2021-04-07 21-34-06

Screenshot from 2021-04-07 21-34-29
no user exists with uid 4 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x] screenshots/GIFs are attached 📎 in case of UI updation
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software 

Thanks!

### CODE REVIEW

**Review by pydevsg — COMMENTED** [review]
Looks good to me @gaurav2699 🎉 
Please add a screenshot of the change before and after you made the changes 😅 .

**Comment by pydevsg** [comment]
Also, @gaurav2699  next time make sure to use a local branch instead of your `main` branch to push the changes.

**Comment by gaurav2699** [comment]
Definitely @pydevsg, thanks a lot!

**Comment by gaurav2699** [comment]
@pydevsg I added screenshots. Thanks!

**Comment by pydevsg** [comment]
Last but not least squash commits when you make so many commits.

**Comment by gaurav2699** [comment]
sure @pydevsg. I dont know why commits from my previous PR's that got merger are also here. Maybe because I didn't change the branch. I will squash it and make sure I use a different branch next time. Thanks

**Review by Tlazypanda — APPROVED** [review]
@gaurav2699 LGTM :tada: For squashing the commits you may use `git rebase -i HEAD~no.of.commits ` and then set as required.

**Comment by cesswairimu** [comment]
Looking good :tada: ...I think we need to confirm with @jywarren if we want to delete user's nodes once the user is deleted once we get a green light on that we are good to merge here. Thanks you both

**Review by RuthNjeri — COMMENTED** [review]
Thanks for working on this @gaurav2699, I do agree with Cess, we need confirmation on whether a user's node should be deleted once they are out of the system...I wonder how this would affect nodes with co-authors or nodes that are important in the system...perhaps we should have a system  ID for a "user"?? That maybe replaces the node uid when a user is deleted...

**Comment by gaurav2699** [comment]
Yes @RuthNjeri. I also now think its not a good idea to delete the nodes when the user who created the node is deleted because we might lose some important nodes due to this, and there might be nodes with multiple authors which should not be deleted. Having a system ID makes sense, so we can show it as deleted user or something else like Anonymous maybe.

**Comment by gaurav2699** [comment]
Lets see what @jywarren thinks of this and I will make changes according to that.

**Comment by jywarren** [comment]
Hi all, i appreciate this conversation so much. Great work identifying the issue which i now see is affecting not only #9417 but also #9527, confirmed that we have some revisions without user records. (44698, 69032 uids in the database). 

Agreed that we should not allow this to happen but also THANK YOU for triple checking on the policy of preserving data before approving and merging this. Great call.

I'm not 100% sure either. I think we really almost NEVER delete a user, so it's interesting to me to try to figure out how this happened in the first place. 

For one, I see that https://publiclab.org/wiki/revisions/getting-started and https://publiclab.org/wiki/revisions/spectral-workbench-api both show missing authors, and both around 8 years ago. So I wonder if this is no longer a risk; it's not like we've seen any user deletion recently. 

With that in mind I think i approve this! I'll check once more and then merge it. Thanks again!!!

File: app/models/user.rb [hunk 1]
```diff
@@ -46,10 +46,10 @@ module Frequency
   # validates_attachment_content_type :photo_file_name, :content_type => %w(image/jpeg image/jpg image/png)
 
   has_many :images, foreign_key: :uid
-  has_many :node, foreign_key: 'uid'
+  has_many :node, foreign_key: 'uid', dependent: :destroy
```
Comment (jywarren) [inline app/models/user.rb:49]: Confirmed that this will, when the user is destroyed, delete all the nodes and revisions:

https://guides.rubyonrails.org/association_basics.html#why-associations-questionmark

**Review by jywarren — APPROVED** [review]
